{% set name = "PolyRound" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PolyRound-{{ version }}.tar.gz
  sha256: 744c08bed5e6457e6bc205e6dbf2168a1ee0a6f2488a3052bad19e7cda883807

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.2
    - pandas >=1.2
    - python-dateutil >=2.8
    - python-libsbml >=5.18
    - scipy >=1.4
    - optlang >=1.4
    - cobra >=0.20

test:
  imports:
    - PolyRound
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/csb.ethz/PolyRound
  summary: A python package for rounding polytopes.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Theorell
